sectors/urls.py
from django.conf.urls import url, include
from . import views, forms


urlpatterns = [
    url(r'^$', views.sector_list, name='list'),
    url(r'(?P<sector_pk>\d+)/(?P<job_pk>\d+)/apply/$', views.apply_view, name='apply'),
    url(r'(?P<sector_pk>\d+)/t(?P<job_pk>\d+)/$', views.text_detail, name='text'),
    url(r'(?P<sector_pk>\d+)/q(?P<job_pk>\d+)/$', views.quiz_detail, name='quiz'),
    url(r'(?P<pk>\d+)/$', views.sector_detail, name='detail'),
]

work_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from tastypie.api import Api
from sectors.api.resources import CvsResource

v1_api = Api(api_name='v1')
v1_api.register(CvsResource())

from . import views

urlpatterns = [
    url(r'^job_categories/', include('sectors.urls', namespace='sectors')),
    url(r'^admin/', admin.site.urls),
    url(r'^search/', views.IndexView),

    url(r'^$', views.hello_world),
    url(r'^api/', include(v1_api.urls)),
]

urlpatterns += staticfiles_urlpatterns()

sectors/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models


# Create your models here.


class Cvs(models.Model):
    name = models.TextField(default="")
    email = models.TextField(default="")
    motivation = models.TextField(default="")

    def __str__(self):
        return self.name

class Sector(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField(default="")

    def __str__(self):
        return self.title


class Job(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    sector = models.ForeignKey(Sector)

    class Meta:
        abstract = True
        ordering = ['order', ]

    def __str__(self):
        return self.title


class Text(Job):
    content = models.TextField(blank=True, default="")

    def get_absolute_url(self):
        return reverse('sectors:text', kwargs={
            'sector_pk': self.sector_id,
            'job_pk': self.id
        })


class Quiz(Job):
    total_questions = models.IntegerField(default=4)

    class Meta:
        verbose_name_plural = "Quizzes"

    def get_absolute_url(self):
        return reverse('sectors:quiz', kwargs={
            'sector_pk': self.sector_id,
            'job_pk': self.id
        })


class Question(models.Model):
    quiz = models.ForeignKey(Quiz)
    order = models.IntegerField(default=0)
    prompt = models.TextField(default="")

    class Meta:
        ordering = ['order', ]

    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    def __str__(self):
        return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)

class TrueFalseQuestion(Question):
    pass

class Answer(models.Model):
    question = models.ForeignKey(Question)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=250)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.text

sectors/forms.py
from django import forms

from django.forms import ModelForm
from django.core import validators
from .models import Cvs


def must_be_empty(value):
    if value:
        raise forms.ValidationError('is not empty')

class ApplyForm(ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    verify_email = forms.EmailField(label="Please verify your email address", widget=forms.TextInput(attrs={'class':'form-control'}))
    motivation = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))
    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="Leave empty",
                               validators=[must_be_empty])
    class Meta:
        model = Cvs
        fields = ['name', 'email', 'motivation']

    def clean(self):
        cleaned_data = super(ApplyForm, self).clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('verify_email')

        if email != verify:
            raise forms.ValidationError(
                "You need to enter the same email in both fields"
            )

sectors/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import ApplyForm
from .models import Cvs

from itertools import chain

# Create your views here.

from . import models, forms

from .models import Sector, Job, Question


def sector_list(request):
    sectors = Sector.objects.all()
    return render(request, 'sectors/sector_list.html', {'sectors': sectors})

def sector_detail(request, pk):
    sector = get_object_or_404(models.Sector, pk=pk)
    jobs = sorted(chain(sector.text_set.all(), sector.quiz_set.all()),
                  key=lambda job: job.order)
    return render(request, 'sectors/sector_detail.html', {
        'sector': sector,
        'jobs': jobs
    })


def text_detail(request, sector_pk, job_pk):
    job = get_object_or_404(models.Text, sector_id=sector_pk, pk=job_pk)
    return render(request, 'sectors/job_detail.html', {'job': job})


def quiz_detail(request, sector_pk, job_pk):
    job = get_object_or_404(models.Quiz, sector_id=sector_pk, pk=job_pk)
    return render(request, 'sectors/job_detail.html', {'job': job})


def apply_view(request, sector_pk, job_pk):
    form = forms.ApplyForm()
    job = get_object_or_404(models.Text, sector_id=sector_pk, pk=job_pk)
    if request.method == 'POST':
        form = forms.ApplyForm(request.POST)
        if form.is_valid():
            send_mail(
                'Application from {}'.format(form.cleaned_data['name']),
                form.cleaned_data['motivation'],
                '{name} <{email}>'.format(**form.cleaned_data),
                ['Jamsie@teamie.com']
            )
            messages.add_message(request, messages.SUCCESS,
                                 'Thanks for your application!')


            cvs = form.save()
            return HttpResponseRedirect(reverse('sectors:apply', kwargs={'sector_pk': sector_pk, 'job_pk': job_pk}))

    return render(request, 'sectors/apply_form.html', {'job': job, 'form': form})


    ## as you can see above, the views of job_detail and apply are the same but
    ## they need to named different as the html reference is different.

    ## also, since we didn't have to create new arguments for this page
    ## the Job class is enough...

work_site/views.py
from django.shortcuts import render
from sectors.models import Job

def hello_world(request):
    return render(request, 'home.html')

from django.http import HttpResponse
from django.template import loader, Context



from django.views import generic
from django.shortcuts import render
from sectors.models import Job

class IndexView(generic.ListView):
    template_name = 'search_results.html'
    page_template = 'base.html'
    context_object_name = 'all_movies'
    model = Job

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context.update({
            'all_genres': Job.objects.all(),
            'page_title': 'Latest'
        })
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Job.objects.filter(title__icontains=query)
        else:
            return Job.objects.all()

sectors/templates/sectors/apply.html
{% extends 'layout.html' %}

{% block title %}{{ job.title }} - {{ job.sector.title }}{% endblock %}

{% block content %}
    <article>
        <h3>{{ job.title }}</h3>

    <div>

    <form class="well form-horizontal" action=" " method="post"  id="contact_form">
<fieldset>

<!-- Form Name -->
<legend>Apply today!</legend>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">First Name</label>
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input  name="first_name" placeholder="First Name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label" >Last Name</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
  <input name="last_name" placeholder="Last Name" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Text input-->
       <div class="form-group">
  <label class="col-md-4 control-label">E-Mail</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
  <input name="email" placeholder="E-Mail Address" class="form-control"  type="text">
    </div>
  </div>
</div>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">Phone #</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
  <input name="phone" placeholder="(845)555-1212" class="form-control" type="text">
    </div>
  </div>
</div>


<!-- Text input-->

<div class="form-group">
  <label class="col-md-4 control-label">City</label>
    <div class="col-md-4 inputGroupContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
  <input name="city" placeholder="city" class="form-control"  type="text">
    </div>
  </div>
</div>

<!-- Select Basic -->

<div class="form-group">
  <label class="col-md-4 control-label">Country</label>
    <div class="col-md-4 selectContainer">
    <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
    <select name="Country" class="form-control selectpicker" >
      <option value=" " >Please select your country</option>
      <option>Netherlands</option>
      <option>Belgium</option>
      <option >UK</option>
      <option >US</option>
    </select>
  </div>
</div>
</div>


<!-- Success message -->
<div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4">
      <button type="submit" class="btn btn-warning" ><a href="{% url 'sectors:thankyou' sector_pk=job.sector.pk job_pk=job.pk %}">Send</a><span class="glyphicon glyphicon-send"></span></button>
  </div>
</div>

</fieldset>
</form>
</div>
    </div><!-- /.container -->
    </article>


{% endblock %}

sectors/templates/sectors/apply_form.html
{% extends 'layout.html' %}

{% block title %}Apply{% endblock %}

{% block content %}
    <div class="page-header">
  <h1>Application Form <small>for the position of {{ job.title }}</small></h1>
</div>
    <div class="form-group">
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input class='form-control' type="submit">
        </form>
    </div>
{% endblock %}

<hidden>To add the apply page. It is important to understand that pk can be used however, change the added apply piece
    everywhere.
</hidden>

sectors/templates/sectors/job_detail.html
{% extends 'layout.html' %}

{% block title %}{{ job.title }} - {{ job.sector.title }}{% endblock %}

{% block content %}
    <article>


        <div class="page-header">
            <h2><a href="{% url 'sectors:detail' pk=job.sector.pk %}">{{ job.sector.title }}</a></h2>
        </div>
        <h3>{{ job.title }}</h3>
        {{ job.content|linebreaks }}
        <p><a href="{% url 'sectors:apply' sector_pk=job.sector.pk job_pk=job.pk %}">Apply</a></p>

    </article>
{% endblock %}

<hidden>To add the apply page. It is important to understand that pk can be used however, change the added apply piece
    everywhere.
</hidden>

sectors/templates/sectors/question.html
{% extends "layout.html" %}

{% block title %}Available Sectors{% endblock %}

{% block content %}
<div class="panel-body">
    {% for question in questions %}
        <div class="card">
            <header><a href="{% url 'sectors:detail' pk=sector.pk %}">{{ sector.title }}</a></header>
            <div class="card-copy">
              {{ sector.description }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

sectors/templates/sectors/sector_detail.html
{% extends "layout.html" %}
{% block title %}{{ sector.title }}{% endblock %}

{% block content %}
    <div class="page-header">
  <h1> {{ sector.title }}</h1>
        {{ sector.description }}
</div>
    <article>

        <section>
            {% for job in jobs %}
                <h3>
                    <a href="{{ job.get_absolute_url }}">{{ job.title }}</a>
                </h3>
                {{ job.description }}
            {% endfor %}
        </section>
    </article>
{% endblock %}

sectors/templates/sectors/sector_list.html
{% extends "layout.html" %}

{% block title %}Available Sectors{% endblock %}

{% block content %}
<div class="panel-body">
    {% for sector in sectors %}
        <div class="card">
            <header><a href="{% url 'sectors:detail' pk=sector.pk %}">{{ sector.title }}</a></header>
            <div class="card-copy">
              {{ sector.description }}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

sectors/templates/sectors/thankyou.html
{% extends 'layout.html' %}

{% block title %}{{ job.title }} - {{ job.sector.title }}{% endblock %}

{% block content %}
    <article>
        Thank you for application for the position of: <h3>{{ job.title }}</h3>
    </article>
{% endblock %}

<hidden>To add the apply page. It is important to understand that pk can be used however, change the added apply piece everywhere.</hidden>

templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there{% endblock %}


{% block content %}<div class="page-header">
  <h1> The world of work</h1>
</div>{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!doctype html>
<html>
<head>

<script>dataLayer = [{
    'path':{{ request.path }} }];</script>

    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-P466F6S');</script>
    <!-- End Google Tag Manager -->
</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P466F6S"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->



<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Staffing Group</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'views.hello_world' %}">Home</a></li>
            <li><a href="{% url 'sectors:list' %}">Job Categories</a></li>
{#            <li><a href="#contact">Contact</a></li>#}
{#            <li class="dropdown">#}
{#              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>#}
{#              <ul class="dropdown-menu">#}
{#                <li><a href="#">Action</a></li>#}
{#                <li><a href="#">Another action</a></li>#}
{#                <li><a href="#">Something else here</a></li>#}
{#                <li role="separator" class="divider"></li>#}
{#                <li class="dropdown-header">Nav header</li>#}
{#                <li><a href="#">Separated link</a></li>#}
{#                <li><a href="#">One more separated link</a></li>#}
{#              </ul>#}
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
{#            <li><a href="../navbar/">Default</a></li>#}
{#            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>#}
{#            <li><a href="../navbar-fixed-top/">Fixed top</a></li>#}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>



<div class="site-container">





    {% block content %}{% endblock %}
    {% if messages %}
            <div class="row">
                {% for message in messages %}
                    <div data-alert class="alert-box {{ message.tags }} radius">
                    {{ message }}
                    <a href="#" class="close">&times;</a>
                {% endfor %}
                </div>

            </div>
        {% endif %}


</div>
</body>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

templates/layout_backup.html
{% load static from staticfiles %}
<!doctype html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>


<div class="site-container">











    <nav>
        <a href="{% url 'views.hello_world' %}">Home</a>
        <a href="{% url 'sectors:list' %}">Jobs</a>
    </nav>
    {% if messages %}
        <div class="row">
            {% for message in messages %}
                <div data-alert class="alert-box {{ message.tags }} radius">
                {{ message }}
                <a href="#" class="close">&times;</a>
            {% endfor %}
            </div>

        </div>
    {% endif %}

    {% block content %}{% endblock %}
</div>
</body>

</html>

templates/search_results.html
{% extends "layout.html" %}

{% block title %}
  <title>{{ job.title }}</title> {% endblock %}

{% block content %}
    <form method="GET" action="" id="searchform">
    <input class="searchfield" id="searchbox" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search..."/>
</form>

{% endblock %}